_target_: src.models.BaseModule
net:
  _target_: src.models.CRIS
  clip_pretrain: pretrain/RN50.pt
  word_len: 77
  fpn_in: [512, 1024, 1024]
  fpn_out: [256, 512, 1024]
  vis_dim: 512
  word_dim: 1024
  num_layers: 3
  num_head: 8
  dim_ffn: 2048
  dropout: 0.2
  intermediate: false
  cris_pretrain: pretrain/cris_best_single.pth

threshold: 0.35

loss_fn: 
  _target_: monai.losses.DiceCELoss
  lambda_dice: 1.0
  lambda_ce: 0.2
optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 2.0e-5
  weight_decay: 0.001
scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  factor: 0.1
  patience: 5
