defaults:
  - model_checkpoint.yaml
  - early_stopping.yaml
  - model_summary.yaml
  - rich_progress_bar.yaml
  - lr_monitor.yaml
  - _self_

model_checkpoint:
  dirpath: ${paths.output_dir}/checkpoints
  filename: "epoch_{epoch:03d}"
  monitor: "val_dice_epoch"
  mode: "max"
  save_last: false
  auto_insert_metric_name: false

early_stopping:
  monitor: "val_dice_epoch"
  patience: 20
  min_delta: 0.0001
  mode: "max"

model_summary:
  max_depth: -1
