# @package _global_

defaults:
  - _self_
  - datamodule: ???
  - model: ???
  - callbacks: default.yaml
  - logger: null
  - trainer: default.yaml
  - paths: default.yaml
  - extras: default.yaml
  - hydra: default.yaml

  # experiment configs allow for version control of specific hyperparameters
  # e.g. best hyperparameters for given model and datamodule
  - experiment: null

task_name: "eval" # "pred" or "eval"

tags: ["dev"]


# Default prompts for each models

# Default path for all of the datasets
data_root: ${paths.data_dir}

img_size: ??? # 224 or 352
tokenizer_type: ??? # clipseg or biomedclip
context_length: ??? # 77 for clipseg, 256 for biomedclip
prompt_type: ??? # Any element or combination of P0, P1, P2, ... P9
train_data_num: 1.0 # 1.0 for full data or number of data to use for training


override_prompt: null # null or str
zero_prompt: false

# The directory to save the output
output_masks_dir: null

use_ckpt: true

# passing checkpoint path is necessary for evaluation
ckpt_path: null

seed: 42


